name: do

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - run: |
        while true; do curl --silent --show-error --fail --trace-ascii dump --trace-time https://distroless.dev/v2 || break; cat dump; sleep 10; done
