name: do

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/setup-go@v3
    - uses: actions/checkout@v3
    - run: while true; do go run . || break; sleep 10; done
